public enum ActionType
{
    NULL,
    MOTIVATION,
    CHECK_INVENTORY,
    USE_ITEM_FROM_INVENTORY,
    PICK_UP_ITEM,
    MOVE_TO_PICKUP,
    MOVE_TO_STATION,
    USE_RECIPE_FROM_INVENTORY,
    USE_RECIPE_AT_STATION,
    STORE_ITEMS_AT_STATION,
    RETRIEVE_ITEM_FROM_STORAGE
}