public enum GoalType
{
    NULL,
    SATISFIED,
    MOTIVATION,
    FIND_ITEM,
    CHECK_MEMORY,
    USE_ITEM_FROM_INVENTORY,
    PICK_UP_ITEM,
    MOVE_TO_ITEM,
    CHECK_INTERACTION,
    USE_RECIPE_FROM_INVENTORY,
    USE_RECIPE_AT_STATION,
    STORE_ITEMS_AT_STATION,
    CHECK_STATIONS_FOR_INTERACTION,
    CHECK_ITEMS_FOR_INTERACTION,
    USE_STATION_FOR_INTERACTION,
    MOVE_TO_STATION,
    ADD_TO_STORAGE,
    SATISFY_MOVE_TO_STATION,
    SATISFY_MOVE_TO_ITEM,
    SATISFY_USE_ITEM_FROM_INVENTORY,
    COMPLETE_RECIPE_AT_STATION,
    COMPLETE_PICK_UP_ITEM,
    COMPLETE_RECIPE_FROM_INVENTORY,
    RETRIEVE_ITEM_FROM_STORAGE

}